package org.example.healthcare.common;

import com.stripe.exception.StripeException;
import com.stripe.model.PaymentIntent;
import com.stripe.model.Refund;
import com.stripe.model.Transfer;
import com.stripe.model.TransferReversal;
import com.stripe.net.RequestOptions;
import com.stripe.param.PaymentIntentCreateParams;
import com.stripe.param.RefundCreateParams;
import com.stripe.param.TransferCreateParams;
import com.stripe.param.TransferReversalCollectionCreateParams;
import lombok.extern.slf4j.Slf4j;
import org.example.healthcare.common.exception.BusinessException;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.util.Map;

/**
 * Facade over the Stripe Java SDK for payment operations.
 *
 * <p>All monetary amounts are converted to bani (minor units) via {@link RonAmount}
 * before calling Stripe — never {@code double} or direct multiplication.
 *
 * <p>Idempotency keys are generated by callers so that retry-safe behaviour is
 * guaranteed at the service layer.
 *
 * <p>PAN-like patterns are never logged; only Stripe object IDs (pi_…, ch_…, tr_…) appear in logs.
 */
@Slf4j
@Service
public class StripePaymentService {

    @Value("${stripe.api.key:sk_test_placeholder}")
    private String secretKey;

    @Value("${app.payments.stripe-enabled:false}")
    private boolean stripeEnabled;

    // ── PaymentIntent ─────────────────────────────────────────────────────────

    /**
     * Creates a Stripe PaymentIntent with {@code automatic} capture and
     * {@code automatic_payment_methods} enabled (supports 3DS/SCA automatically).
     *
     * @param amount           charge amount in RON (major units)
     * @param currency         ISO 4217 lowercase code — must be "ron"
     * @param stripeCustomerId patient's Stripe customer ID (may be null for guest checkout)
     * @param bookingId        used as idempotency key prefix
     * @param metadata         PaymentIntent metadata per §4 row 11
     * @return the newly-created {@link PaymentIntent}
     */
    public PaymentIntent createPaymentIntent(BigDecimal amount,
                                             String currency,
                                             String stripeCustomerId,
                                             String bookingId,
                                             Map<String, String> metadata) {
        long amountBani = RonAmount.of(amount).toBani();

        PaymentIntentCreateParams.Builder builder = PaymentIntentCreateParams.builder()
                .setAmount(amountBani)
                .setCurrency(currency.toLowerCase())
                .setCaptureMethod(PaymentIntentCreateParams.CaptureMethod.AUTOMATIC)
                .setAutomaticPaymentMethods(
                        PaymentIntentCreateParams.AutomaticPaymentMethods.builder()
                                .setEnabled(true)
                                .build())
                .putAllMetadata(metadata);

        if (stripeCustomerId != null && !stripeCustomerId.isBlank()) {
            builder.setCustomer(stripeCustomerId);
        }
        if (bookingId != null) {
            builder.setTransferGroup("booking_" + bookingId);
        }

        RequestOptions opts = RequestOptions.builder()
                .setIdempotencyKey("pi:" + bookingId)
                .build();

        try {
            PaymentIntent pi = PaymentIntent.create(builder.build(), opts);
            log.info("Created PaymentIntent {} for booking {} ({} bani)", pi.getId(), bookingId, amountBani);
            return pi;
        } catch (StripeException e) {
            log.error("Failed to create PaymentIntent for booking {}: code={} message={}",
                    bookingId, e.getCode(), e.getMessage());
            throw new BusinessException("Payment creation failed: " + e.getCode());
        }
    }

    /**
     * Backwards-compatible overload used by existing {@code PaymentServiceImpl} calls
     * that do not yet pass metadata.
     */
    public String createPaymentIntent(BigDecimal amount, String currency, String stripeCustomerId) {
        long amountBani = RonAmount.of(amount).toBani();

        PaymentIntentCreateParams params = PaymentIntentCreateParams.builder()
                .setAmount(amountBani)
                .setCurrency(currency.toLowerCase())
                .setCaptureMethod(PaymentIntentCreateParams.CaptureMethod.AUTOMATIC)
                .setAutomaticPaymentMethods(
                        PaymentIntentCreateParams.AutomaticPaymentMethods.builder()
                                .setEnabled(true).build())
                .build();

        try {
            PaymentIntent pi = PaymentIntent.create(params);
            log.info("Created PaymentIntent {}", pi.getId());
            return pi.getId();
        } catch (StripeException e) {
            log.error("Failed to create PaymentIntent: {}", e.getMessage());
            throw new BusinessException("Payment creation failed: " + e.getCode());
        }
    }

    // ── Capture (legacy — kept for ConsultationServiceImpl compatibility) ─────

    public void capturePaymentIntent(String paymentIntentId) {
        if (!stripeEnabled) {
            log.info("[STRIPE STUB] capturePaymentIntent skipped — app.payments.stripe-enabled=false. intentId={}", paymentIntentId);
            return;
        }
        try {
            PaymentIntent pi = PaymentIntent.retrieve(paymentIntentId);
            if ("requires_capture".equals(pi.getStatus())) {
                pi.capture();
                log.info("Captured PaymentIntent {}", paymentIntentId);
            }
        } catch (StripeException e) {
            log.error("Failed to capture PaymentIntent {}: {}", paymentIntentId, e.getMessage());
            throw new BusinessException("Payment capture failed: " + e.getCode());
        }
    }

    // ── Transfer ──────────────────────────────────────────────────────────────

    /**
     * Transfers net amount from the platform account to the medic's/clinic's Express account.
     *
     * @param paymentIntentId Stripe PI id (used to look up the source charge)
     * @param stripeAccountId destination connected account (acct_…)
     * @param netAmount       amount to transfer in RON (major units)
     * @param bookingId       for transfer_group labelling
     * @param paymentId       used as idempotency key: {@code paymentId:release}
     * @param chargeId        Stripe Charge id (ch_…) for source_transaction
     * @return Stripe Transfer ID (tr_…)
     */
    public String transferToAccount(String paymentIntentId,
                                    String stripeAccountId,
                                    BigDecimal netAmount,
                                    String bookingId,
                                    String paymentId,
                                    String chargeId) {
        long netBani = RonAmount.of(netAmount).toBani();

        TransferCreateParams.Builder builder = TransferCreateParams.builder()
                .setAmount(netBani)
                .setCurrency("ron")
                .setDestination(stripeAccountId)
                .setTransferGroup("booking_" + bookingId);

        if (chargeId != null && !chargeId.isBlank()) {
            builder.setSourceTransaction(chargeId);
        }

        RequestOptions opts = RequestOptions.builder()
                .setIdempotencyKey(paymentId + ":release")
                .build();

        try {
            Transfer transfer = Transfer.create(builder.build(), opts);
            log.info("Created Transfer {} ({} bani) to {}", transfer.getId(), netBani, stripeAccountId);
            return transfer.getId();
        } catch (StripeException e) {
            log.error("Failed to create Transfer for payment {}: {}", paymentId, e.getMessage());
            throw new BusinessException("Transfer failed: " + e.getCode());
        }
    }

    /**
     * Backwards-compatible overload for existing service code.
     */
    public String transferToAccount(String paymentIntentId, String stripeAccountId, BigDecimal netAmount) {
        return transferToAccount(paymentIntentId, stripeAccountId, netAmount, null, null, null);
    }

    // ── Transfer reversal (clawback) ──────────────────────────────────────────

    /**
     * Reverses a transfer back to the platform (used when a dispute resolves for the patient
     * after funds were already released).
     *
     * @param transferId Stripe Transfer id (tr_…)
     * @param paymentId  for idempotency key: {@code paymentId:reverse}
     */
    public void reverseTransfer(String transferId, String paymentId) {
        RequestOptions opts = RequestOptions.builder()
                .setIdempotencyKey(paymentId + ":reverse")
                .build();

        try {
            Transfer transfer = Transfer.retrieve(transferId);
            TransferReversalCollectionCreateParams params =
                    TransferReversalCollectionCreateParams.builder().build();
            TransferReversal reversal = transfer.getReversals().create(params, opts);
            log.info("Reversed Transfer {} → reversal {}", transferId, reversal.getId());
        } catch (StripeException e) {
            log.error("Failed to reverse Transfer {} for payment {}: {}", transferId, paymentId, e.getMessage());
            throw new BusinessException("Transfer reversal failed: " + e.getCode());
        }
    }

    // ── Refund ────────────────────────────────────────────────────────────────

    /**
     * Issues a full or partial refund on a PaymentIntent.
     *
     * @param paymentIntentId Stripe PI id
     * @param amount          amount to refund in RON; {@code null} means full refund
     * @param paymentId       for idempotency key: {@code paymentId:refund:<reason>}
     * @param reason          refund reason string (e.g. "requested_by_customer")
     */
    public void refund(String paymentIntentId, BigDecimal amount, String paymentId, String reason) {
        RefundCreateParams.Builder builder = RefundCreateParams.builder()
                .setPaymentIntent(paymentIntentId);

        if (amount != null) {
            builder.setAmount(RonAmount.of(amount).toBani());
        }
        if (reason != null && !reason.isBlank()) {
            try {
                builder.setReason(RefundCreateParams.Reason.valueOf(reason.toUpperCase()));
            } catch (IllegalArgumentException ignored) {
                // Unknown reason — let Stripe use default
            }
        }

        String idempotencyKey = paymentId != null
                ? paymentId + ":refund:" + (reason != null ? reason : "default")
                : null;

        RequestOptions opts = idempotencyKey != null
                ? RequestOptions.builder().setIdempotencyKey(idempotencyKey).build()
                : null;

        try {
            Refund refund = opts != null
                    ? Refund.create(builder.build(), opts)
                    : Refund.create(builder.build());
            log.info("Created Refund {} for PaymentIntent {}", refund.getId(), paymentIntentId);
        } catch (StripeException e) {
            log.error("Failed to create Refund for {}: {}", paymentIntentId, e.getMessage());
            throw new BusinessException("Refund failed: " + e.getCode());
        }
    }

    /** Backwards-compatible overload. */
    public void refund(String paymentIntentId, BigDecimal amount) {
        refund(paymentIntentId, amount, null, null);
    }

    // ── Cancel ────────────────────────────────────────────────────────────────

    public void cancelPaymentIntent(String paymentIntentId) {
        try {
            PaymentIntent pi = PaymentIntent.retrieve(paymentIntentId);
            if (!"canceled".equals(pi.getStatus()) && !"succeeded".equals(pi.getStatus())) {
                pi.cancel();
                log.info("Cancelled PaymentIntent {}", paymentIntentId);
            }
        } catch (StripeException e) {
            log.error("Failed to cancel PaymentIntent {}: {}", paymentIntentId, e.getMessage());
            throw new BusinessException("PaymentIntent cancellation failed: " + e.getCode());
        }
    }
}
